routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/diagnostico/pendientes', 'ControlerDiagnostico@pendientes')->name('diagnostico.pendientes');

Route::group(['middleware' => ['web']], function () {
    Route::resource('departamento','ControladorDepartamento');
    Route::resource('usuarios','ControlerUser');
    Route::resource('paciente','ControlerPaciente');
    Route::resource('especialidad','ControlerEspecialidad');
    Route::resource('sintoma','ControlerSintoma');
    Route::resource('enfermedad','ControlerEnfermedad');
    Route::resource('turnos','ControlerTurno');
    Route::resource('diagnostico','ControlerDiagnostico');
    Route::resource('categoriaSintoma','ControllerCategoriaSintoma');
    Route::get('updatepassview/{usuario}', 'ControlerUser@updatepassview')->name('updatepassview');
    Route::patch('updatepass/{usuario}', 'ControlerUser@updatepass')->name('updatepass');
});

app/Paciente.php
<?php

namespace App;

use DB;
use Illuminate\Database\Eloquent\Model;

class Paciente extends Model
{
    protected $table = 'pacientes';
	
	public function departamento()
    {
        return $this->belongsTo('App\Departamento');
    }

    public function nombre_completo()
    {
    	return $this->attributes['nombre']." ".$this->attributes['paterno']." ".$this->attributes['materno'];
    }

    public function telefonos()
    {
    	if((isset($this->attributes['telefono']))&&(isset($this->attributes['celular']))){
    		return $this->attributes['telefono']."-".$this->attributes['celular'];
    	}else if(isset($this->attributes['telefono'])){
			return $this->attributes['telefono'];
    	}else if(isset($this->attributes['celular'])){
			return $this->attributes['celular'];
    	}else{
			return 'Sin telefono';
    	}
    }

    public function edad()
    {
    	return date_diff(date_create($this->attributes['nacimiento']), date_create('now'))->y;
    }

    public function ultima_visita()
    {
         $diagnosticos = DB::table('diagnosticos')->where('paciente_id', '=', $this->id)->orderBy('created_at', 'desc')->take(1)->get();
         return $diagnosticos;

    }

    public function creacion()
    {
        $aux_date = explode(" ", $this->attributes['nacimiento']);
        return $aux_date[0];
    }

    public function diagnosticos()
    {
        return $this->hasMany('App\Diagnostico');
    }

}

resources/views/paciente/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-plus-circle"></i> Nuevo Paciente</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('paciente.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nombre(s)</label>

                            <div class="col-md-6">
                                <input id="nombre" type="text" class="form-control" onkeyup="this.value=this.value.replace(/[^A-Za-z ]/g,'');"  name="nombre" value="{{ old('nombre') }}" required autofocus>

                                @if ($errors->has('nombre'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('nombre') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('paterno') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Apellido paterno</label>

                            <div class="col-md-6">
                                <input id="paterno" type="text" class="form-control" onkeyup="this.value=this.value.replace(/[^A-Za-z ]/g,'');"  name="paterno" value="{{ old('paterno') }}" required>

                                @if ($errors->has('paterno'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('paterno') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('materno') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Apellido materno</label>

                            <div class="col-md-6">
                                <input id="materno" type="text" class="form-control" onkeyup="this.value=this.value.replace(/[^A-Za-z ]/g,'');"  name="materno" value="{{ old('materno') }}">

                                @if ($errors->has('materno'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('materno') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('documento') ? ' has-error' : '' }}">
                            <label for="documento" class="col-md-4 control-label">DNI</label>

                            <div class="col-md-6">
                                <input id="documento" type="text" class="form-control" name="documento" value="{{ old('documento') }}" onkeypress="return isNumber(event)" required>

                                @if ($errors->has('documento'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('documento') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('departamento_id') ? ' has-error' : '' }}">
                            <label for="departamento_id" class="col-md-4 control-label">Departamento</label>
                            <div class="col-md-6">
                                <select id="departamento_id" name="departamento_id" class="form-control">
                                    @foreach($departamentos as $departamento)
                                    <option value="{{$departamento->id}}" {{ (old('departamento_id') == $departamento->id) ? 'selected':'' }} >
                                    {{$departamento->name}}
                                    </option>
                                    @endforeach
                                </select>
                                @if ($errors->has('departamento_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('departamento_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('nacimiento') ? ' has-error' : '' }}">
                            <label for="carnet" class="col-md-4 control-label">Fecha de nacimiento</label>

                            <div class="col-md-6">
                                <input id="nacimiento" type="date" class="form-control" name="nacimiento" value="{{ old('nacimiento') }}" required>

                                @if ($errors->has('nacimiento'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('nacimiento') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('direccion') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Direccion</label>

                            <div class="col-md-6">
                                <input id="direccion" type="text" class="form-control" name="direccion" value="{{ old('direccion') }}">

                                @if ($errors->has('direccion'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('direccion') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('telefono') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Telefono</label>

                            <div class="col-md-6">
                                <input id="telefono" type="text" class="form-control" name="telefono" value="{{ old('telefono') }}">

                                @if ($errors->has('telefono'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('telefono') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('celular') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Celular</label>

                            <div class="col-md-6">
                                <input id="celular" type="text" class="form-control" name="celular" value="{{ old('celular') }}">

                                @if ($errors->has('celular'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('celular') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                <div class="col-md-6" align="left">
                                    <button type="submit" class="btn btn-block btn-primary">
                                        Registrar
                                    </button>
                                </div>
                                <div class="col-md-6" align="right">
                                    <a class="btn btn-default btn-block" href="{{url()->previous()}}">
                                        Cancelar
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
<script type="text/javascript">
    function isNumber(evt) {
        if(document.getElementById('documento').value.length < 8){
            evt = (evt) ? evt : window.event;
            var charCode = (evt.which) ? evt.which : evt.keyCode;
            if (charCode > 31 && (charCode < 48 || charCode > 57)) {
                return false;
            }
            return true;
        }else{
            return true;
        }
    }
</script>

resources/views/paciente/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-edit"></i> Editar Paciente</div>

                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{route('paciente.update',$paciente->id)}}">

                        <input name="_method" type="hidden" value="PATCH">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nombre(s)</label>

                            <div class="col-md-6">
                                <input id="nombre" type="text" class="form-control" onkeyup="this.value=this.value.replace(/[^A-Za-z ]/g,'');"  name="nombre" value="{{$paciente->nombre}}" required autofocus>

                                @if ($errors->has('nombre'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('nombre') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('paterno') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Apellido paterno</label>

                            <div class="col-md-6">
                                <input id="paterno" type="text" class="form-control" onkeyup="this.value=this.value.replace(/[^A-Za-z ]/g,'');"  name="paterno" value="{{$paciente->paterno}}" required>

                                @if ($errors->has('paterno'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('paterno') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('materno') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Apellido materno</label>

                            <div class="col-md-6">
                                <input id="materno" type="text" class="form-control" onkeyup="this.value=this.value.replace(/[^A-Za-z ]/g,'');"  name="materno" value="{{$paciente->materno}}">

                                @if ($errors->has('materno'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('materno') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('documento') ? ' has-error' : '' }}">
                            <label for="documento" class="col-md-4 control-label">DNI</label>

                            <div class="col-md-6">
                                <input id="documento" type="text" class="form-control" name="documento" value="{{$paciente->documento}}" onkeypress="return isNumber(event)" required>

                                @if ($errors->has('documento'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('carnet') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('departamento_id') ? ' has-error' : '' }}">
                            <label for="departamento_id" class="col-md-4 control-label">Departamento</label>
                            <div class="col-md-6">
                                <select id="departamento_id" name="departamento_id" class="form-control">
                                    @foreach($departamentos as $departamento)
                                    <option value="{{$departamento->id}}" {{ ($paciente->departamento_id == $departamento->id) ? 'selected':'' }} >
                                    {{$departamento->name}}
                                    </option>
                                    @endforeach
                                </select>
                                @if ($errors->has('departamento_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('departamento_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('nacimiento') ? ' has-error' : '' }}">
                            <label for="carnet" class="col-md-4 control-label">Fecha de nacimiento</label>

                            <div class="col-md-6">
                                <input id="nacimiento" type="date" class="form-control" name="nacimiento" value="{{ $paciente->nacimiento}}" required>

                                @if ($errors->has('nacimiento'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('nacimiento') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('direccion') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Direccion</label>

                            <div class="col-md-6">
                                <input id="direccion" type="text" class="form-control" name="direccion" value="{{ $paciente->direccion}}">

                                @if ($errors->has('direccion'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('direccion') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('telefono') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Telefono</label>

                            <div class="col-md-6">
                                <input id="telefono" type="text" class="form-control" name="telefono" value="{{ $paciente->telefono}}">

                                @if ($errors->has('telefono'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('telefono') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('celular') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Celular</label>

                            <div class="col-md-6">
                                <input id="celular" type="text" class="form-control" name="celular" value="{{ $paciente->celular}}">

                                @if ($errors->has('celular'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('celular') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                <div class="col-md-6" align="left">
                                    <button type="submit" class="btn btn-block btn-warning">
                                        Editar
                                    </button>
                                </div>
                                <div class="col-md-6" align="right">
                                    <a class="btn btn-default btn-block" href="{{url()->previous()}}">
                                        Cancelar
                                    </a>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
<script type="text/javascript">
    function isNumber(evt) {
        if(document.getElementById('documento').value.length < 8){
            evt = (evt) ? evt : window.event;
            var charCode = (evt.which) ? evt.which : evt.keyCode;
            if (charCode > 31 && (charCode < 48 || charCode > 57)) {
                return false;
            }
            return true;
        }else{
            return true;
        }
    }
</script>

resources/views/paciente/historial.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-address-book"></i> Datos personales del paciente
                </div>
                <div class="panel-body">
                    <div class="col-md-2 col-md-offset-1" style="vertical-align: center;">
                        <br/><i class="fa fa-address-card fa-5x"></i>
                    </div>
                    <div class="col-md-4">
                        <label class="control-label">Nombre completo : </label>{{ $paciente->nombre_completo() }}<br/>
                        <label class="control-label">DNI: </label>{{ $paciente->documento }}<br/>
                        <label class="control-label">Departamento : </label>{{ $paciente->departamento->name }}<br/>
                        <label class="control-label">Fecha de nacimiento : </label>{{ $paciente->nacimiento }}<br/>
                        <label class="control-label">Edad : </label>{{ $paciente->edad() }} años<br/>
                    </div>
                    <div class="col-md-4 col-md-offset-1">
                        <label class="control-label">Direccion : </label>@if(isset($paciente->direccion)) {{ $paciente->direccion }} @else - @endif<br/>
                        <label class="control-label">Telefono : </label>@if(isset($paciente->telefono)) {{ $paciente->telefono }} @else - @endif<br/>
                        <label class="control-label">Celular : </label>@if(isset($paciente->celular)) {{ $paciente->telefono }} @else - @endif<br/>
                        <label class="control-label">Ultima visita : </label>@if($paciente->ultima_visita()->count()>0) @foreach($paciente->ultima_visita() as $ultima) {{$ultima->updated_at}} @endforeach @else Primera visita @endif<br/>
                        <label class="control-label">Registro : </label>@if(isset($paciente->created_at)) {{ $paciente->creacion() }} @else - @endif<br/>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-md-offset-0">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-file-text"></i> Historial medico
                </div>
                <div class="panel-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Medico</th>
                                <th width="10%">Fecha y Hora</th>
                                <th width="20%">Sintomas</th>
                                <th width="15%">Diagnostico</th>
                                <th>Recomendaciones</th>
                                <th>Ver</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $num = 1; ?>
                            @foreach($paciente->diagnosticos as $diagnostico)
                                <tr>
                                    <td>{{$num++}}</td>
                                    <td>{{$diagnostico->user->name}}<br/>{{$diagnostico->user->especialidad->nombre}}</td>
                                    <td>{{$diagnostico->fecha_creacion()}}<br/>{{$diagnostico->hora_creacion()}}</td>
                                    <td>
                                        <?php $aux = 0; ?>
                                        @foreach($diagnostico->sintomas as $sintoma_lista)
                                        {{ $sintoma_lista->nombre }}
                                        <?php $aux++; ?>
                                        @if($aux<$diagnostico->sintomas->count()) , @endif
                                        @endforeach
                                    </td>
                                    <td>
                                        @foreach($diagnostico->enfermedades as $enfermedad_lista)
                                            - {{ $enfermedad_lista->nombre }}<br/>
                                        @endforeach
                                    </td>
                                    <td>
                                        <p>{{ $diagnostico->recomendacion }}</p>
                                    </td>
                                    <td>
                                        <a href="{{route('diagnostico.show',$diagnostico->id)}}" class="btn btn-success"><i class="fa fa-file-text"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/paciente/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
	    <div class="row">
	        <div class="col-md-10 col-md-offset-1">
	            <div class="panel panel-default">
	                <div class="panel-heading">
	                	<i class="fa fa-address-book"></i> Pacientes
	                	<div class="pull-right">
							<a href="{{route('paciente.create')}}" class="btn btn-primary btn-xs pull-right"> <i class="fa fa-plus-circle"></i> Nuevo</a>
	                	</div>
	                </div>

	                <div class="panel-body">
						<table class="table table-striped">
							<thead>
								<tr>
									<th>No.</th>
									<th>Nombre</th>
									<th>DNI</th>
									<th>Exp</th>
									<th>Edad</th>
									<th>Tel-Cel</th>
									<th>Hist.</th>
									<th>Editar</th>
									<th>Eliminar</th>
								</tr>
							</thead>
							<tbody>
								<?php $num = 1; ?>
								@foreach($pacientes as $paciente)
									<tr>
										<td>{{$num++}}</td>
										<td>{{$paciente->nombre_completo()}}</td>
										<td>{{$paciente->documento}}</td>
										<td>{{$paciente->departamento->abreviatura}}</td>
										<td>{{$paciente->edad()}}</td>
										<td>{{$paciente->telefonos()}}</td>
										<td>
											<a href="{{route('paciente.show',$paciente->id)}}" class="btn btn-success"><i class="fa fa-file-text"></i></a>
										</td>
										<td>
											<a href="{{route('paciente.edit',$paciente->id)}}" class="btn btn-warning"><i class="fa fa-edit"></i></a>
										</td>
										<td>
											<form class="" action="{{route('paciente.destroy',$paciente->id)}}" method="post">
												<input type="hidden" name="_method" value="delete">
												<input type="hidden" name="_token" value="{{ csrf_token() }}">
												<button type="submit" class="btn btn-danger" onclick="return confirm('Esta seguro de eliminar este registro?');"><i class="fa fa-trash"></i></button>
											</form>
										</td>
									</tr>
								@endforeach
							</tbody>
						</table>
	                </div>
	            </div>
	        </div>
	    </div>
	</div>
@endsection