routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/diagnostico/pendientes', 'ControlerDiagnostico@pendientes')->name('diagnostico.pendientes');

Route::group(['middleware' => ['web']], function () {
    Route::resource('departamento','ControladorDepartamento');
    Route::resource('usuarios','ControlerUser');
    Route::resource('paciente','ControlerPaciente');
    Route::resource('especialidad','ControlerEspecialidad');
    Route::resource('sintoma','ControlerSintoma');
    Route::resource('enfermedad','ControlerEnfermedad');
    Route::resource('turnos','ControlerTurno');
    Route::resource('diagnostico','ControlerDiagnostico');
    Route::resource('categoriaSintoma','ControllerCategoriaSintoma');
    Route::get('updatepassview/{usuario}', 'ControlerUser@updatepassview')->name('updatepassview');
    Route::patch('updatepass/{usuario}', 'ControlerUser@updatepass')->name('updatepass');
});

app/Diagnostico.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Diagnostico extends Model
{
    protected $table = 'diagnosticos';

    public function fecha_creacion()
    {
    	$fecha_creacion = explode(" ", $this->attributes['created_at']);
    	return $fecha_creacion[0];
    }

    public function hora_creacion()
    {
    	$fecha_creacion = explode(" ", $this->attributes['created_at']);
    	return $fecha_creacion[1];
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function paciente()
    {
    	return $this->belongsTo('App\Paciente');
    }

    public function enfermedades()
    {
    	return $this->belongsToMany('App\Enfermedad');
    }

    public function sintomas()
    {
    	return $this->belongsToMany('App\Sintoma');
    }

}

resources/views/diagnostico/create.blade.php
@extends('layouts.app')

    {!! Html::style('css/bootstrap-select.min.css') !!}
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                	<i class="fa fa-plus-circle"></i> Crear Diagnostico
                </div>
                <div class="panel-body">
					<form class="form-horizontal" role="form" method="POST" action="{{route('diagnostico.store')}}" name="formulario_historial">
						{{ csrf_field() }}


                        <div class="form-group{{ ($errors->has('paciente_id')) ? $errors->first('paciente_id') : '' }}">
                            <label for="paciente_id" class="col-md-4 control-label">Paciente</label>
                            <div class="col-md-6">
                                <select class="form-control selectpicker" name="paciente_id" id="paciente_id" data-live-search="true">
                                    @foreach($pacientes as $paciente)
                                        <option value="{{$paciente->id}}">{{$paciente->nombre_completo()}}</option>
                                    @endforeach
                                </select>
                                {!! $errors->first('paciente_id','<p class="help-block">:message</p>') !!}
                            </div>
                        </div>

                        <div class="form-group{{ ($errors->has('sintomas')) ? $errors->first('sintomas') : '' }}">
                            <label for="sintomas" class="col-md-4 control-label">Sintomas</label>
                            <div class="col-md-6">
                                <select class="form-control selectpicker" name="sintomas[]" id="sintomas" multiple="multiple" data-live-search="true">
                                    @foreach($sintomas as $sintoma)
                                        <option value="{{$sintoma->id}}">{{$sintoma->nombre}}</option>
                                    @endforeach
                                </select>
                                {!! $errors->first('sintomas','<p class="help-block">:message</p>') !!}
                            </div>
                        </div>
						
                        <div class="form-group{{ ($errors->has('enfermedades')) ? $errors->first('enfermedades') : '' }}">
                            <label for="enfermedades" class="col-md-4 control-label">Enfermedades</label>
                            <div class="col-md-6">
                                <select class="form-control selectpicker" name="enfermedades[]" id="enfermedades" multiple="multiple" data-live-search="true">
                                    @foreach($enfermedades as $enfermedad)
                                        <option value="{{$enfermedad->id}}">{{$enfermedad->nombre}}</option>
                                    @endforeach
                                </select>
                                {!! $errors->first('enfermedades','<p class="help-block">:message</p>') !!}
                            </div>
                        </div>

                        <div class="form-group{{ ($errors->has('recomendacion')) ? $errors->first('recomendacion') : '' }}">
                            <label for="recomendacion" class="col-md-4 control-label">Recomendacion</label>
                            <div class="col-md-6">
                                <textarea type="text" id="recomendacion" name="recomendacion" class="form-control" placeholder="Ingresa las recomendaciones aqui" required>
                                </textarea>
                                {!! $errors->first('recomendacion','<p class="help-block">:message</p>') !!}
                            </div>
                        </div>

                        <div class="form-group{{ ($errors->has('retorno')) ? $errors->first('retorno') : '' }}">
                            <label for="retorno" class="col-md-4 control-label">Fecha de retorno</label>
                            <div class="col-md-6">
                                <input type="date" name="retorno" id="retorno" class="form-control">
                                {!! $errors->first('retorno','<p class="help-block">:message</p>') !!}
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('receta') ? ' has-error' : '' }}">
                            <label for="receta" class="col-md-4 control-label">Receta medica</label>
                            <div class="col-md-6" id="medicamentos" >
                                <input type="text" id="receta1" name="receta[]" class="form-control" placeholder="Ingresa un medicamento" required>
                                @if ($errors->has('tipo_usuario'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('tipo_usuario') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <button id="remove-medicamento" class="btn btn-danger pull-right">
                                <i class="fa fa-minus-square"></i> Quitar Medicamento
                            </button>
                            <button id="add-medicamento" class="btn btn-info pull-right">
                                <i class="fa fa-plus-square"></i> Añadir Medicamento
                            </button>

                        </div>

                        <input type="text" name="estado" id="estado" class="form-control" value="Terminado" style="display: none;">
						
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                <div class="col-md-6" align="left">
                                    <button type="submit" class="btn btn-block btn-primary">
                                        Registrar
                                    </button>
                                </div>
                                <div class="col-md-6" align="right">
                                    <a class="btn btn-default btn-block" href="{{url()->previous()}}">
                                        Cancelar
                                    </a>
                                </div>
                            </div>
                        </div>

					</form>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        var medicamentosCount =document.formulario_historial.elements['receta[]'].length;


        var addMedicamento = function () {
            var medicamentosDiv = document.getElementById('medicamentos');
            var newWidget = document.createElement("input");
            newWidget.setAttribute('class','form-control');
            newWidget.setAttribute('name','receta[]');
            newWidget.setAttribute('id','receta'+toString(medicamentosCount));
            newWidget.setAttribute('placeholder',"Ingresa un medicamento");
            medicamentosCount++;

            $(newWidget).appendTo(medicamentosDiv);
        };

        var removeMedicamento = function () {
            if (medicamentosCount < 1) return;

            var medicamentosDiv = document.getElementById('medicamentos');
            var ultimoMedicamento = medicamentosDiv.removeChild(medicamentosDiv.lastElementChild);

            ultimoMedicamento.remove();

            medicamentosCount--;
        };
        if (medicamentosCount === 0) addMedicamento();
        $('#add-medicamento').click(function (e) {
            e.preventDefault();
            addMedicamento();
        });

        $('#remove-medicamento').click(function (e) {
            e.preventDefault();
            removeMedicamento();
        });

    });
</script>
@endsection

    {!! Html::script('js/jquery.min.js') !!}

    {!! Html::script('js/bootstrap-select.min.js') !!}

resources/views/diagnostico/edit.blade.php
@extends('layouts.app')

    {!! Html::style('css/bootstrap-select.min.css') !!}

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-edit"></i> Editar Diagnostico
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{route('diagnostico.update',$diagnostico->id)}}">
                        <input name="_method" type="hidden" value="PATCH">
                        {{ csrf_field() }}

                        <div class="form-group{{ ($errors->has('paciente_id')) ? $errors->first('paciente_id') : '' }}">
                            <label for="paciente_id" class="col-md-4 control-label">Paciente</label>
                            <div class="col-md-6">
                                <select class="form-control selectpicker" name="paciente_id" id="paciente_id" data-live-search="true">
                                    @foreach($pacientes as $paciente)
                                        <option value="{{$paciente->id}}"  {{ ($diagnostico->paciente_id == $paciente->id) ? 'selected':'' }} >{{$paciente->nombre_completo()}}</option>
                                    @endforeach
                                </select>
                                {!! $errors->first('paciente_id','<p class="help-block">:message</p>') !!}
                            </div>
                        </div>

                        <div class="form-group{{ ($errors->has('sintomas')) ? $errors->first('sintomas') : '' }}">
                            <label for="sintomas" class="col-md-4 control-label">Sintomas</label>
                            <div class="col-md-6">
                                <select class="form-control selectpicker" name="sintomas[]" id="sintomas" multiple="multiple" data-live-search="true">
                                    @foreach($sintomas as $sintoma)
                                        <option value="{{$sintoma->id}}"
                                        @foreach($diagnostico->sintomas as $sintoma_lista)
                                            {{ ($sintoma->id == $sintoma_lista->id) ? 'selected':'' }}
                                        @endforeach
                                            >{{$sintoma->nombre}}</option>
                                    @endforeach
                                </select>
                                {!! $errors->first('sintomas','<p class="help-block">:message</p>') !!}
                            </div>
                        </div>
                        
                        <div class="form-group{{ ($errors->has('enfermedades')) ? $errors->first('enfermedades') : '' }}">
                            <label for="enfermedades" class="col-md-4 control-label">Enfermedades</label>
                            <div class="col-md-6">
                                <select class="form-control selectpicker" name="enfermedades[]" id="enfermedades" multiple="multiple" data-live-search="true">
                                    @foreach($enfermedades as $enfermedad)
                                        <option value="{{$enfermedad->id}}"
                                        @foreach($diagnostico->enfermedades as $enfermedad_lista)
                                            {{ ($enfermedad->id == $enfermedad_lista->id) ? 'selected':'' }}
                                        @endforeach
                                            >{{$enfermedad->nombre}}</option>
                                    @endforeach
                                </select>
                                {!! $errors->first('enfermedades','<p class="help-block">:message</p>') !!}
                            </div>
                        </div>

                        <div class="form-group{{ ($errors->has('recomendacion')) ? $errors->first('recomendacion') : '' }}">
                            <label for="recomendacion" class="col-md-4 control-label">Recomendacion</label>
                            <div class="col-md-6">
                                <textarea type="text" id="recomendacion" name="recomendacion" class="form-control" placeholder="Ingresa las recomendaciones aqui" required>{{$diagnostico->recomendacion}}</textarea>
                                {!! $errors->first('recomendacion','<p class="help-block">:message</p>') !!}
                            </div>
                        </div>

                        <div class="form-group{{ ($errors->has('retorno')) ? $errors->first('retorno') : '' }}">
                            <label for="retorno" class="col-md-4 control-label">Fecha de retorno</label>
                            <div class="col-md-6">
                                <input type="date" name="retorno" id="retorno" class="form-control" value="{{$diagnostico->retorno}}">
                                {!! $errors->first('retorno','<p class="help-block">:message</p>') !!}
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('receta') ? ' has-error' : '' }}">
                            <label for="receta" class="col-md-4 control-label">Receta medica</label>
                            <div class="col-md-6">
                                <select id="receta" name="receta" class="form-control">
                                    <option value="Emitida" {{ ($diagnostico->receta == 'Emitida') ? 'selected':'' }}>Emitida</option>
                                    <option value="No emitida" {{ ($diagnostico->receta == 'No emitida') ? 'selected':'' }}>No emitida</option>
                                </select>
                                @if ($errors->has('tipo_usuario'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('tipo_usuario') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                <div class="col-md-6" align="left">
                                    <button type="submit" class="btn btn-block btn-warning">
                                        Editar
                                    </button>
                                </div>
                                <div class="col-md-6" align="right">
                                    <a class="btn btn-default btn-block" href="{{url()->previous()}}">
                                        Cancelar
                                    </a>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

    {!! Html::script('js/jquery.min.js') !!}

    {!! Html::script('js/bootstrap-select.min.js') !!}

resources/views/diagnostico/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                	<i class="fa fa-medkit"></i> Diagnosticos Realizados
                </div>

                <div class="panel-body">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>No.</th>
								<th>Paciente</th>
								<th>Edad</th>
								<th>Fecha</th>
								<th>Hora</th>
								<th>Revisar</th>
							</tr>
						</thead>
						<tbody>
							<?php $num = 1; ?>
							@foreach($diagnosticos as $diagnostico)
								<tr>
									<td>{{$num++}}</td>
									<td>{{$diagnostico->paciente->nombre_completo()}}</td>
									<td>{{$diagnostico->paciente->edad()}}</td>
									<td>{{$diagnostico->fecha_creacion()}}</td>
									<td>{{$diagnostico->hora_creacion()}}</td>
									<td>
										<a href="{{route('diagnostico.show',$diagnostico->id)}}" class="btn btn-success"><i class="fa fa-file-text"></i></a>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/diagnostico/pendientes.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                	<i class="fa fa-user-md"></i> Diagnosticos Pendientes
                	<div class="pull-right">
						<a href="{{route('diagnostico.create')}}" class="btn btn-primary btn-xs pull-right"> <i class="fa fa-plus-circle"></i> Nuevo</a>
                	</div>
                </div>

                <div class="panel-body">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>No.</th>
								<th>Paciente</th>
								<th>Edad</th>
								<th>Fecha</th>
								<th>Hora</th>
								<th>Pendiente</th>
								<th>Eliminar</th>
							</tr>
						</thead>
						<tbody>
							<?php $num = 1; ?>
							@foreach($diagnosticos as $diagnostico)
								<tr>
									<td>{{$num++}}</td>
									<td>{{$diagnostico->paciente->nombre_completo()}}</td>
									<td>{{$diagnostico->paciente->edad()}}</td>
									<td>{{$diagnostico->fecha_creacion()}}</td>
									<td>{{$diagnostico->hora_creacion()}}</td>
									<td>
										<a href="{{route('diagnostico.edit',$diagnostico->id)}}" class="btn btn-warning"><i class="fa fa-edit"></i></a>
									</td>
									<td>
										<form class="" action="{{route('diagnostico.destroy',$diagnostico->id)}}" method="post">
											<input type="hidden" name="_method" value="delete">
											<input type="hidden" name="_token" value="{{ csrf_token() }}">
											<button type="submit" class="btn btn-danger" onclick="return confirm('Esta seguro de eliminar este registro?');"><i class="fa fa-trash"></i></button>
										</form>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/diagnostico/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-file-text"></i> Ver Diagnostico
                </div>
                <div class="panel-body">
                    <form action="{{route('diagnostico.index')}}">

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-md-5 control-label">Paciente : </label>
                                    <div class="col-md-6" align="left">
                                        <h4>{{ $diagnostico->paciente->nombre_completo() }}</h4>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-5 control-label">Edad : </label>
                                    <div class="col-md-6" align="left">
                                        <h4>{{ $diagnostico->paciente->edad() }} Años</h4>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-5 control-label">Doctor : </label>
                                    <div class="col-md-6" align="left">
                                        <h4>{{ $diagnostico->user->name }}</h4>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-5 control-label">Especialidad : </label>
                                    <div class="col-md-6" align="left">
                                        <h4>{{ $diagnostico->user->especialidad->nombre }}</h4>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-5 control-label">Fecha : </label>
                                    <div class="col-md-6" align="left">
                                        <h4>{{ $diagnostico->fecha_creacion() }}</h4>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-5 control-label">Hora : </label>
                                    <div class="col-md-6" align="left">
                                        <h4>{{ $diagnostico->hora_creacion() }}</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">

                                <div class="form-group">
                                    <label class="col-md-5 control-label">Sintomas : </label>
                                    <div class="col-md-6">
                                        @foreach($diagnostico->sintomas as $sintoma_lista)
                                            - {{ $sintoma_lista->nombre }}<br/>
                                        @endforeach
                                    </div>
                                </div>
                                <br/><br/>
                                <div class="form-group">
                                    <label class="col-md-5 control-label">Enfermedades : </label>
                                    <div class="col-md-6">
                                        @foreach($diagnostico->enfermedades as $enfermedad_lista)
                                            - {{ $enfermedad_lista->nombre }}<br/>
                                        @endforeach
                                    </div>
                                </div>
                                <br/>
                                <div class="form-group">
                                    <label class="col-md-5 control-label">Recomendacion : </label>
                                    <div class="col-md-6" align="left">
                                        <p>{{ $diagnostico->recomendacion }}</p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-5 control-label">Receta medica : </label>
                                    <div class="col-md-6" align="left">
{{--                                        <h4>{{ $diagnostico->receta }}</h4>--}}
                                        @foreach(explode(",",$diagnostico->receta) as $receta)
                                            - {{ $receta }}<br/>
                                        @endforeach
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-5 control-label">Debe retornar : </label>
                                    <div class="col-md-6" align="left">
                                        <h4>{{ $diagnostico->retorno }}</h4>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                <!--div class="col-md-6" align="left">
                                    <button type="submit" class="btn btn-block btn-success">
                                        Imprimir
                                    </button>
                                </div-->
                                <div class="col-md-6" align="right">
                                    <a class="btn btn-default btn-block" href="{{url()->previous()}}">
                                        Volver
                                    </a>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection