routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/diagnostico/pendientes', 'ControlerDiagnostico@pendientes')->name('diagnostico.pendientes');

Route::group(['middleware' => ['web']], function () {
    Route::resource('departamento','ControladorDepartamento');
    Route::resource('usuarios','ControlerUser');
    Route::resource('paciente','ControlerPaciente');
    Route::resource('especialidad','ControlerEspecialidad');
    Route::resource('sintoma','ControlerSintoma');
    Route::resource('enfermedad','ControlerEnfermedad');
    Route::resource('turnos','ControlerTurno');
    Route::resource('diagnostico','ControlerDiagnostico');
    Route::resource('categoriaSintoma','ControllerCategoriaSintoma');
    Route::get('updatepassview/{usuario}', 'ControlerUser@updatepassview')->name('updatepassview');
    Route::patch('updatepass/{usuario}', 'ControlerUser@updatepass')->name('updatepass');
});

app/Departamento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Departamento extends Model
{
    protected $table = 'departamentos';

    public function usuarios()
    {
    	return $this->hasMany('App\User');
    }

    public function pacientes()
    {
    	return $this->hasMany('App\Paciente');
    }

}

resources/views/departamento/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                	<i class="fa fa-plus-circle"></i> Crear Departamento
                </div>
                <div class="panel-body">
					<form class="form-horizontal" role="form" method="POST" action="{{route('departamento.store')}}">
						{{ csrf_field() }}
						
						<div class="form-group{{ ($errors->has('departamento_name')) ? $errors->first('departamento_name') : '' }}">
							<label for="departamento_name" class="col-md-4 control-label">Nombre</label>
							<div class="col-md-6">
								<input type="text" id="departamento_name" name="departamento_name" class="form-control" placeholder="Ingresa el nombre aqui" required autofocus>
								{!! $errors->first('departamento_name','<p class="help-block">:message</p>') !!}
							</div>
						</div>

						<div class="form-group{{ ($errors->has('abreviatura')) ? $errors->first('abreviatura') : '' }}">
							<label for="abreviatura" class="col-md-4 control-label">Abreviatura</label>
							<div class="col-md-6">
								<input type="text" id="abreviatura" name="abreviatura" class="form-control" placeholder="Ingresa la abreviatura aqui" required>
								{!! $errors->first('abreviatura','<p class="help-block">:message</p>') !!}
							</div>
						</div>
						
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                <div class="col-md-6" align="left">
                                    <button type="submit" class="btn btn-block btn-primary">
                                        Registrar
                                    </button>
                                </div>
                                <div class="col-md-6" align="right">
                                    <a class="btn btn-default btn-block" href="{{url()->previous()}}">
                                        Cancelar
                                    </a>
                                </div>
                            </div>
                        </div>

					</form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/departamento/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                	<i class="fa fa-edit"></i> Editar Departamento
                </div>

                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{route('departamento.update',$departamento->id)}}">
                        <input name="_method" type="hidden" value="PATCH">
						{{ csrf_field() }}

						<div class="form-group{{ ($errors->has('departamento_name')) ? $errors->first('departamento_name') : '' }}">
                            <label for="departamento_name" class="col-md-4 control-label">Nombre</label>
                            <div class="col-md-6">
    							<input type="text" id="departamento_name" name="departamento_name" class="form-control" placeholder="Ingresa el nombre aqui" value="{{$departamento->name}}" autofocus>
    							{!! $errors->first('departamento_name','<p class="help-block">:message</p>') !!}
                            </div>
						</div>

                        <div class="form-group{{ ($errors->has('abreviatura')) ? $errors->first('abreviatura') : '' }}">
                            <label for="departamento_name" class="col-md-4 control-label">Abreviatura</label>
                            <div class="col-md-6">
                                <input type="text" id="abreviatura" name="abreviatura" class="form-control" placeholder="Ingresa la breviatura aqui" value="{{$departamento->abreviatura}}">
                                {!! $errors->first('abreviatura','<p class="help-block">:message</p>') !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                <div class="col-md-6" align="left">
                                    <button type="submit" class="btn btn-block btn-warning">
                                        Editar
                                    </button>
                                </div>
                                <div class="col-md-6" align="right">
                                    <a class="btn btn-default btn-block" href="{{url()->previous()}}">
                                        Cancelar
                                    </a>
                                </div>
                            </div>
                        </div>
					</form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/departamento/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                	<i class="fa fa-cubes"></i> Departamentos
                	<div class="pull-right">
						<a href="{{route('departamento.create')}}" class="btn btn-primary btn-xs pull-right"> <i class="fa fa-plus-circle"></i> Nuevo</a>
                	</div>
                </div>

                <div class="panel-body">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>No.</th>
								<th>Nombre</th>
								<th>Abreviatura</th>
								<th>Editar</th>
								<th>Eliminar</th>
							</tr>
						</thead>
						<tbody>
							<?php $num = 1; ?>
							@foreach($departamentos as $departamento)
								<tr>
									<td>{{$num++}}</td>
									<td>{{$departamento->name}}</td>
									<td>{{$departamento->abreviatura}}</td>
									<td>
										<a href="{{route('departamento.edit',$departamento->id)}}" class="btn btn-warning"><i class="fa fa-edit"></i></a>
									</td>
									<td>
										<form class="" action="{{route('departamento.destroy',$departamento->id)}}" method="post">
											<input type="hidden" name="_method" value="delete">
											<input type="hidden" name="_token" value="{{ csrf_token() }}">
											<button type="submit" class="btn btn-danger" onclick="return confirm('Esta seguro de eliminar este registro?');"><i class="fa fa-trash"></i></button>
										</form>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection